### ISSUE TITLE
Write an ERC721 contract with custom errors

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-contracts#28]
As suggested by @scorpion9979 in https://github.com/paulrberg/prb-contracts/discussions/21.

**Comment by PaulRBerg** [comment]
I'm going to close this issue because OpenZeppelin has started working on this. See [EIP-6093](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-6093.md).

**Comment by PaulRBerg** [comment]
Cc @scorpion9979 you might be interested to track OpenZeppelin's progress on their V5 (which will come with EIP-6093-powered contracts).

**Comment by scorpion9979** [comment]
> Cc @scorpion9979 you might be interested to track OpenZeppelin's progress on their V5 (which will come with EIP-6093-powered contracts).

Thanks for the tip! I just added a GitHub notification for OpenZeppelin's releases.
